module Kata::SpecialOfferType
  THREE_FOR_TWO = 'THREE_FOR_TWO'.freeze
  TEN_PERCENT_DISCOUNT = 'TEN_PERCENT_DISCOUNT'.freeze
  TWO_FOR_AMOUNT = 'TWO_FOR_AMOUNT'.freeze
  FIVE_FOR_AMOUNT = 'FIVE_FOR_AMOUNT'.freeze
end
